### ISSUE TITLE
undefined method `types' for #<RDL::Type::VarType:0x007fb64b5dac10 @name=:u>

### ISSUE THREAD

**Issue by backus** [plum-umd/rdl#24]
Awesome tool! I ran into an error when using `rdl_query`:

```sh
$ rdl_query '(...) { (...) -> %bool } -> .'
/Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/types/union.rb:83:in `match': undefined method `types' for #<RDL::Type::VarType:0x007fb64b5dac10 @name=:u> (NoMethodError)
Did you mean?  type
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/types/method.rb:311:in `match'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/types/method.rb:316:in `match'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:58:in `block (3 levels) in method_type_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:57:in `each'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:57:in `block (2 levels) in method_type_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:55:in `each'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:55:in `block in method_type_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:54:in `each'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:54:in `method_type_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:91:in `block in rdl_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/switch.rb:13:in `off'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/lib/rdl/query.rb:73:in `rdl_query'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/rdl-2.0.1/bin/rdl_query:24:in `<top (required)>'
	from /Users/johnbackus/.gem/ruby/2.3.3/bin/rdl_query:22:in `load'
	from /Users/johnbackus/.gem/ruby/2.3.3/bin/rdl_query:22:in `<main>'
```

I was looking for all methods that take take a block that expects a boolean return for https://github.com/bbatsov/rubocop/issues/4446

**Comment by jeffrey-s-foster** [comment]
Thanks! Looking into this further, there seems to be an obvious bug with the way matching is done with several kinds of types (unions, intersections, and generics, at least). I will work on fixing this.

**Comment by jeffrey-s-foster** [comment]
Fixed in `dev` branch.

**Comment by backus** [comment]
Thanks @jeffrey-s-foster!
