### ISSUE TITLE
rdl_query and RDL.query cannot parse complex class name

### ISSUE THREAD

**Issue by baban** [plum-umd/rdl#69]
I encount error like a below.
When class name include '::', query dump error.

```bash
rdl_query 'ActiveRecord::Base#logger'
```

```
/home/baban/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rdl-2.1.0/lib/rdl/query.rb:98:in `block in query': Don't know how to handle query (RuntimeError)
        from /home/baban/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rdl-2.1.0/lib/rdl/switch.rb:13:in `off'
        from /home/baban/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rdl-2.1.0/lib/rdl/query.rb:73:in `query'
        from /home/baban/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rdl-2.1.0/bin/rdl_query:24:in `<top (required)>'
        from /home/baban/.rbenv/versions/2.4.1/bin/rdl_query:22:in `load'
        from /home/baban/.rbenv/versions/2.4.1/bin/rdl_query:22:in `<main>'
```

```ruby
RDL.query 'ActiveRecord::Base#logger'
```

```
RuntimeError: Don't know how to handle query
        from (irb):3
```

**Comment by mckaz** [comment]
This is fixed in the dev branch, which will be merged with master shortly.
