### ISSUE TITLE
Cannot receive generically-typed argument

### ISSUE THREAD

**Issue by mame** [plum-umd/rdl#74]
Is this intentional?

```ruby
require "rdl"
extend RDL::Annotate

type "(Array<Integer>) -> %any"
def foo(x)
end

foo([1, 2, 3])
```

```
$ ruby t.rb
Traceback (most recent call last):
	11: from t.rb:8:in `<main>'
	10: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/wrap.rb:48:in `foo'
	 9: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/switch.rb:13:in `off'
	 8: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/wrap.rb:62:in `block in foo'
	 7: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:237:in `check_arg_types'
	 6: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/switch.rb:13:in `off'
	 5: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:239:in `block in check_arg_types'
	 4: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:239:in `each_with_index'
	 3: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:239:in `each'
	 2: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:240:in `block (2 levels) in check_arg_types'
	 1: from /home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/method.rb:140:in `pre_cond?'
/home/mame/local/lib/ruby/gems/2.5.0/gems/rdl-2.1.0/lib/rdl/types/generic.rb:43:in `member?': No type parameters defined for Array (RuntimeError)
```

**Comment by mckaz** [comment]
This should work with `require 'types/core'`.
